"""baseline: capture current live schema

Revision ID: bf0e9bc5cbb9
Revises: 
Create Date: 2026-08-23 11:26:20.955670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0e9bc5cbb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('drones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('mass_kg', sa.Float(), nullable=True),
    sa.Column('frame_type', sa.String(), nullable=True),
    sa.Column('motor_count', sa.Integer(), nullable=True),
    sa.Column('max_thrust_n', sa.Float(), nullable=True),
    sa.Column('battery_capacity_mah', sa.Float(), nullable=True),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('propeller_diameter_in', sa.Float(), nullable=True),
    sa.Column('motor_kv', sa.Integer(), nullable=True),
    sa.Column('battery_cells', sa.Integer(), nullable=True),
    sa.Column('wing_area_m2', sa.Float(), nullable=True),
    sa.Column('lift_to_drag_ratio', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drones_id'), 'drones', ['id'], unique=False)
    op.create_index(op.f('ix_drones_owner_id'), 'drones', ['owner_id'], unique=False)
    op.create_table('scene_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_objects_created_at'), 'scene_objects', ['created_at'], unique=False)
    op.create_index(op.f('ix_scene_objects_drone_id'), 'scene_objects', ['drone_id'], unique=False)
    op.create_index(op.f('ix_scene_objects_id'), 'scene_objects', ['id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('battery', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('roll', sa.Float(), nullable=True),
    sa.Column('pitch', sa.Float(), nullable=True),
    sa.Column('yaw', sa.Float(), nullable=True),
    sa.Column('flight_state', sa.String(), nullable=True),
    sa.Column('desired_roll', sa.Float(), nullable=True),
    sa.Column('desired_pitch', sa.Float(), nullable=True),
    sa.Column('desired_yaw', sa.Float(), nullable=True),
    sa.Column('motor_pwm_1', sa.Float(), nullable=True),
    sa.Column('motor_pwm_2', sa.Float(), nullable=True),
    sa.Column('motor_pwm_3', sa.Float(), nullable=True),
    sa.Column('motor_pwm_4', sa.Float(), nullable=True),
    sa.Column('accel_x', sa.Float(), nullable=True),
    sa.Column('accel_y', sa.Float(), nullable=True),
    sa.Column('accel_z', sa.Float(), nullable=True),
    sa.Column('gyro_x', sa.Float(), nullable=True),
    sa.Column('gyro_y', sa.Float(), nullable=True),
    sa.Column('gyro_z', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_drone_id'), 'telemetry', ['drone_id'], unique=False)
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_index(op.f('ix_telemetry_timestamp'), 'telemetry', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_timestamp'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_index(op.f('ix_telemetry_drone_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_scene_objects_id'), table_name='scene_objects')
    op.drop_index(op.f('ix_scene_objects_drone_id'), table_name='scene_objects')
    op.drop_index(op.f('ix_scene_objects_created_at'), table_name='scene_objects')
    op.drop_table('scene_objects')
    op.drop_index(op.f('ix_drones_owner_id'), table_name='drones')
    op.drop_index(op.f('ix_drones_id'), table_name='drones')
    op.drop_table('drones')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
